In [31]:
import tensorflow as tf

In [32]:
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34, 31]

In [33]:
# build a simple tensorflow datgaset 
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

In [34]:
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
-108
31
-1
32
34
31


In [35]:
# select specific elements
for sales in tf_dataset.take(3):
    print(sales.numpy())

21
22
-108


In [36]:
# apply transofrmations

tf_dataset = tf_dataset.filter(lambda x: x > 0)

for sales in tf_dataset:
    print(sales.numpy())

21
22
31
32
34
31


In [37]:
# convert this dollar into RWF
tf_dataset = tf_dataset.map(lambda x: x * 1400)

for sales in tf_dataset:
    print(sales.numpy())

29400
30800
43400
44800
47600
43400


In [38]:
# randomly rearrage the element
tf_dataset = tf_dataset.shuffle(3)

for sales in tf_dataset:
    print(sales.numpy())

43400
44800
29400
43400
47600
30800


In [39]:
tf_dataset = tf_dataset.batch(2)

for sales in tf_dataset:
    print(sales.numpy())

[30800 43400]
[47600 29400]
[44800 43400]


In [47]:
# doing all this input pipeline in single line
tf_datasets = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

for slaes in tf_datasets:
    print(sales.numpy())

[30800 43400 47600]
[30800 43400 47600]
[30800 43400 47600]
[30800 43400 47600]
[30800 43400 47600]
[30800 43400 47600]
[30800 43400 47600]
[30800 43400 47600]


In [48]:
tf_datasets = tf_datasets.filter(lambda y: y > 0).map(lambda z: z * 1400).shuffle(3).batch(3)

for sales in tf_datasets:
    print(sales.numpy())

[43400 29400 44800]
[47600 43400 30800]


In [49]:
# performing input pipeline with images dataset

In [51]:
image_ds = tf.data.Dataset.list_files("lionel_messi/*", shuffle=False)