In [31]:
import tensorflow as tf

In [32]:
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34, 31]

In [33]:
# build a simple tensorflow datgaset 
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

In [34]:
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
-108
31
-1
32
34
31


In [35]:
# select specific elements
for sales in tf_dataset.take(3):
    print(sales.numpy())

21
22
-108


In [36]:
# apply transofrmations

tf_dataset = tf_dataset.filter(lambda x: x > 0)

for sales in tf_dataset:
    print(sales.numpy())

21
22
31
32
34
31


In [37]:
# convert this dollar into RWF
tf_dataset = tf_dataset.map(lambda x: x * 1400)

for sales in tf_dataset:
    print(sales.numpy())

29400
30800
43400
44800
47600
43400


In [38]:
# randomly rearrage the element
tf_dataset = tf_dataset.shuffle(3)

for sales in tf_dataset:
    print(sales.numpy())

43400
44800
29400
43400
47600
30800


In [39]:
tf_dataset = tf_dataset.batch(2)

for sales in tf_dataset:
    print(sales.numpy())

[30800 43400]
[47600 29400]
[44800 43400]


In [55]:
# doing all this input pipeline in single line
tf_datasets = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

for slaes in tf_datasets:
    print(sales.numpy())

[47600 43400 30800]
[47600 43400 30800]
[47600 43400 30800]
[47600 43400 30800]
[47600 43400 30800]
[47600 43400 30800]
[47600 43400 30800]
[47600 43400 30800]


In [56]:
tf_datasets = tf_datasets.filter(lambda y: y > 0).map(lambda z: z * 1400).shuffle(3).batch(3)

for sales in tf_datasets:
    print(sales.numpy())

[29400 43400 44800]
[47600 43400 30800]


In [49]:
# performing input pipeline with images dataset

In [59]:
image_ds = tf.data.Dataset.list_files("image_dataset/*", shuffle=False)

In [60]:
for image in image_ds.take(5):
    print(image)

tf.Tensor(b'image_dataset/02453493f852c0efe8ff951dea5845c4.jpg', shape=(), dtype=string)
tf.Tensor(b'image_dataset/02fa06cf94.jpg', shape=(), dtype=string)
tf.Tensor(b'image_dataset/05b9bac90a.jpg', shape=(), dtype=string)
tf.Tensor(b'image_dataset/088db66e0b.jpg', shape=(), dtype=string)
tf.Tensor(b'image_dataset/0b43460429.jpg', shape=(), dtype=string)


In [61]:
image_ds = image_ds.shuffle(200)

for image in image_ds.take(5):
    print(image)

tf.Tensor(b'image_dataset/1146943f73.jpg', shape=(), dtype=string)
tf.Tensor(b'image_dataset/Lionel-Messi-of-FC-Barcelona.jpg', shape=(), dtype=string)
tf.Tensor(b'image_dataset/0b53cce8c6.jpg', shape=(), dtype=string)
tf.Tensor(b'image_dataset/fc75b07003.jpg', shape=(), dtype=string)
tf.Tensor(b'image_dataset/5a3384f779.jpg', shape=(), dtype=string)


In [62]:
class_names = ["Messi", "Roger"]

In [64]:
# splitting dataset into test, and train dataset
image_count = len(image_ds)
image_count

162

In [65]:
train_ds = image_ds.take(int(image_count * 0.8))
test_ds = image_ds.skip(int(image_count * 0.8))

In [67]:
len(train_ds)

129

In [68]:
len(test_ds)

33