In [31]:
import tensorflow as tf

In [32]:
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34, 31]

In [33]:
# build a simple tensorflow datgaset 
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

In [34]:
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
-108
31
-1
32
34
31


In [35]:
# select specific elements
for sales in tf_dataset.take(3):
    print(sales.numpy())

21
22
-108


In [36]:
# apply transofrmations

tf_dataset = tf_dataset.filter(lambda x: x > 0)

for sales in tf_dataset:
    print(sales.numpy())

21
22
31
32
34
31


In [37]:
# convert this dollar into RWF
tf_dataset = tf_dataset.map(lambda x: x * 1400)

for sales in tf_dataset:
    print(sales.numpy())

29400
30800
43400
44800
47600
43400


In [38]:
# randomly rearrage the element
tf_dataset = tf_dataset.shuffle(3)

for sales in tf_dataset:
    print(sales.numpy())

43400
44800
29400
43400
47600
30800


In [39]:
tf_dataset = tf_dataset.batch(2)

for sales in tf_dataset:
    print(sales.numpy())

[30800 43400]
[47600 29400]
[44800 43400]


In [55]:
# doing all this input pipeline in single line
tf_datasets = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)

for slaes in tf_datasets:
    print(sales.numpy())

[47600 43400 30800]
[47600 43400 30800]
[47600 43400 30800]
[47600 43400 30800]
[47600 43400 30800]
[47600 43400 30800]
[47600 43400 30800]
[47600 43400 30800]


In [56]:
tf_datasets = tf_datasets.filter(lambda y: y > 0).map(lambda z: z * 1400).shuffle(3).batch(3)

for sales in tf_datasets:
    print(sales.numpy())

[29400 43400 44800]
[47600 43400 30800]


In [49]:
# performing input pipeline with images dataset

In [77]:
image_ds = tf.data.Dataset.list_files("image_dataset/*/*", shuffle=False)

In [78]:
for image in image_ds.take(5):
    print(image)

tf.Tensor(b'image_dataset/lionel_messi/02453493f852c0efe8ff951dea5845c4.jpg', shape=(), dtype=string)
tf.Tensor(b'image_dataset/lionel_messi/10_MESSI_JUGADORS-WEB.jpg', shape=(), dtype=string)
tf.Tensor(b'image_dataset/lionel_messi/1211643746.jpg.0.jpg', shape=(), dtype=string)
tf.Tensor(b'image_dataset/lionel_messi/136054219.jpg.0.jpg', shape=(), dtype=string)
tf.Tensor(b'image_dataset/lionel_messi/190703-lionel-messi.jpg', shape=(), dtype=string)


In [79]:
image_ds = image_ds.shuffle(200)

for image in image_ds.take(5):
    print(image)

tf.Tensor(b'image_dataset/roger_federer/rogerfederer_perfect_82463094_646872489387563_6528719341074753867_n.jpg', shape=(), dtype=string)
tf.Tensor(b'image_dataset/lionel_messi/lionel-messi-in-november-2005_kmvg03y9e7621774f558bqqnl.jpg', shape=(), dtype=string)
tf.Tensor(b'image_dataset/roger_federer/833491-jzwrfgakxz-1491130217.jpg', shape=(), dtype=string)
tf.Tensor(b'image_dataset/lionel_messi/lionel-messi-barcelona_s4mt4mvtjyy41gz5noeslzqjt.jpg', shape=(), dtype=string)
tf.Tensor(b'image_dataset/roger_federer/ca717e520880bf40c28015a3d33395db.jfif', shape=(), dtype=string)


In [80]:
class_names = ["Messi", "Roger"]

In [81]:
# splitting dataset into test, and train dataset
image_count = len(image_ds)
image_count

119

In [82]:
train_ds = image_ds.take(int(image_count * 0.8))
test_ds = image_ds.skip(int(image_count * 0.8))

In [83]:
len(train_ds)

95

In [84]:
len(test_ds)

24

In [89]:
# getting labels in our image dataset
sample = 'image_dataset/roger_federer/rogerfederer_perfect_82463094_646872489387563_6528719341074753867_n.jpg'

sample.split("/")[1]

'roger_federer'

In [ ]:
def get_labels